import { useCallback, useEffect, useState } from 'react';
import { ApiError, apiGet } from '../lib/api';
import { useI18n } from '../i18n/useI18n';
import { t as tMsg } from '../i18n/translate';

type Evento = { id: string | number; accion: string; entidad: string; entidad_id: string | null; detalle: Record<string, unknown>; creado_en: string; usuario_origem_codigo: number; nombre: string | null; sobrenome: string | null; empresa: string | null };
function actionLabel(event: Evento): string { const names: Record<string, string> = { CREAR: tMsg('Creación'), BAJA: tMsg('Baja'), REVERSION: tMsg('Reversión'), ACTUALIZAR: tMsg('Actualización') }; return `${names[event.accion] ?? event.accion} · ${event.entidad.replaceAll('_', ' ')}`; }

export function AuditoriaScreen({ token }: { token: string }) {
  const { t, locale } = useI18n();
  const [events, setEvents] = useState<Evento[]>([]); const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading'); const [error, setError] = useState('');
  const load = useCallback(async () => { setStatus('loading'); setError(''); try { const body = await apiGet<{ data: Evento[] }>('/auditoria?limite=100', token); setEvents(body.data); setStatus('ready'); } catch (failure) { setError(failure instanceof ApiError ? failure.message : tMsg('No se pudo consultar la auditoría.')); setStatus('error'); } }, [token]);
  useEffect(() => { void load(); }, [load]);
  return <><header className="ds-page-header"><div className="ds-page-header__text"><h1 className="ds-title">{t('Auditoría')}</h1><p className="ds-secondary">{t('Registro inmutable de las últimas acciones administrativas y financieras.')}</p></div><button type="button" className="ds-btn ds-btn--secondary" disabled={status === 'loading'} onClick={() => void load()}>{status === 'loading' ? t('Actualizando…') : t('Actualizar')}</button></header>{error && <div className="ds-alert ds-alert--danger"><div className="ds-alert__body"><p>{error}</p></div></div>}{status === 'loading' ? <div className="ds-card"><div className="ds-card__body"><div className="ds-skeleton" style={{ height: '8rem' }} /></div></div> : <section className="ds-card"><div className="ds-table-wrap" style={{ border: 0 }}><table className="ds-table ds-table--cards"><thead><tr><th>{t('Fecha y hora')}</th><th>{t('Acción')}</th><th>{t('Usuario')}</th><th>{t('Empresa')}</th></tr></thead><tbody>{events.length === 0 ? <tr><td colSpan={4} className="ds-secondary">{t('Todavía no hay eventos registrados.')}</td></tr> : events.map((event) => <tr key={event.id}><td data-label={t('Fecha y hora')}>{new Intl.DateTimeFormat(locale, { dateStyle: 'short', timeStyle: 'short' }).format(new Date(event.creado_en))}</td><td className="is-strong" data-label={t('Acción')}>{actionLabel(event)}<span className="ds-help" style={{ display: 'block' }}>{event.entidad_id ? t('Registro {id}', { id: event.entidad_id }) : '—'}</span></td><td data-label={t('Usuario')}>{event.nombre ? `${event.nombre} ${event.sobrenome ?? ''}` : t('Código {n}', { n: String(event.usuario_origem_codigo) })}</td><td data-label={t('Empresa')}>{event.empresa ?? t('Grupo')}</td></tr>)}</tbody></table></div></section>}</>;
}
