import { FormEvent, useCallback, useEffect, useState } from 'react';
import { Modal } from '../components/Modal';
import { ApiError, apiGet, apiPost } from '../lib/api';
import { useI18n } from '../i18n/useI18n';
import { t as tMsg } from '../i18n/translate';

type Contact = { id:string|number; tipo_persona:'F'|'J'; ruc:string|null; razon_social:string; nombre_fantasia:string|null; ciudad:string|null; telefono:string|null; celular:string|null; email:string|null };
export function ContrapartesScreen({token}:{token:string}){
 const { t } = useI18n();
 const [rows,setRows]=useState<Contact[]>([]),[status,setStatus]=useState<'loading'|'ready'|'error'>('loading'),[error,setError]=useState(''),[creating,setCreating]=useState(false),[razon,setRazon]=useState(''),[ruc,setRuc]=useState(''),[persona,setPersona]=useState<'F'|'J'>('J'),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setStatus('loading');try{const body=await apiGet<{data:Contact[]}>('/contrapartes',token);setRows(body.data);setStatus('ready');}catch(f){setError(f instanceof ApiError?f.message:tMsg('No se pudieron cargar los contactos.'));setStatus('error');}},[token]);useEffect(()=>{void load();},[load]);
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError('');try{await apiPost('/contrapartes',{tipoPersona:persona,razonSocial:razon,ruc:ruc||undefined},token);setCreating(false);setRazon('');setRuc('');void load();}catch(f){setError(f instanceof ApiError?f.message:tMsg('No se pudo guardar el contacto.'));}finally{setSaving(false);}}
 return <><header className="ds-page-header"><div className="ds-page-header__text"><h1 className="ds-title">{t('Clientes y proveedores')}</h1><p className="ds-secondary">{t('Directorio único del grupo para evitar registros duplicados.')}</p></div><div className="ds-page-header__actions"><button className="ds-btn ds-btn--primary" onClick={()=>setCreating(true)}>{t('Nuevo contacto')}</button></div></header>{status==='error'&&<div className="ds-alert ds-alert--danger"><div className="ds-alert__body"><p>{error}</p></div></div>}{status==='loading'?<div className="ds-stack-2" aria-busy="true">{[1,2,3].map(i=><div key={i} className="ds-skeleton" style={{height:'2rem'}}/>)}</div>:rows.length===0?<div className="ds-empty"><p className="ds-empty__title">{t('No hay clientes ni proveedores')}</p><p className="ds-empty__text">{t('Creá el primer contacto o ingresalo al registrar una cuenta.')}</p></div>:<section className="ds-card"><div className="ds-table-wrap" style={{border:0}}><table className="ds-table ds-table--cards"><thead><tr><th>{t('Razón social')}</th><th>{t('Tipo')}</th><th>{t('RUC')}</th><th>{t('Ciudad')}</th><th>{t('Contacto')}</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td data-label={t('Razón social')} className="is-strong">{row.razon_social}<span className="ds-help" style={{display:'block'}}>{row.nombre_fantasia??''}</span></td><td data-label={t('Tipo')}>{row.tipo_persona==='J'?t('Jurídica'):t('Física')}</td><td data-label={t('RUC')}>{row.ruc??'—'}</td><td data-label={t('Ciudad')}>{row.ciudad??'—'}</td><td data-label={t('Contacto')}>{row.telefono??row.celular??row.email??'—'}</td></tr>)}</tbody></table></div></section>}{creating&&<Modal title={t('Nuevo cliente o proveedor')} onClose={()=>setCreating(false)}><form className="ds-modal__body" onSubmit={submit}><div className="ds-field"><label className="ds-label">{t('Tipo de persona')}</label><select className="ds-select" value={persona} onChange={e=>setPersona(e.target.value as 'F'|'J')}><option value="J">{t('Jurídica')}</option><option value="F">{t('Física')}</option></select></div><div className="ds-field"><label className="ds-label">{t('Razón social o nombre')}</label><input className="ds-input" value={razon} onChange={e=>setRazon(e.target.value)} required autoFocus/></div><div className="ds-field"><label className="ds-label">{t('RUC')} <span className="ds-label__optional">{t('(opcional)')}</span></label><input className="ds-input" value={ruc} onChange={e=>setRuc(e.target.value)}/></div>{error&&<div className="ds-alert ds-alert--danger"><div className="ds-alert__body"><p>{error}</p></div></div>}<footer className="ds-modal__footer"><button type="button" className="ds-btn ds-btn--secondary" onClick={()=>setCreating(false)}>{t('Cancelar')}</button><button className="ds-btn ds-btn--primary" disabled={saving}>{saving?t('Guardando…'):t('Guardar contacto')}</button></footer></form></Modal>}</>;
}
