import { FormEvent, useCallback, useEffect, useState } from 'react';
import { Modal } from '../components/Modal';
import { ApiError, apiGet, apiPost } from '../lib/api';
import type { CurrencyCode } from '../design-system/format';
import { useI18n } from '../i18n/useI18n';
import { t as tMsg } from '../i18n/translate';

type Empresa = { id: string | number; razon_social: string; nombre_fantasia: string | null; ruc: string | null; moneda_base: CurrencyCode; activa: boolean };

export function EmpresasScreen({ token, onChanged }: { token: string; onChanged: () => void }) {
  const { t } = useI18n();
  const [empresas, setEmpresas] = useState<Empresa[]>([]); const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading'); const [error, setError] = useState(''); const [creating, setCreating] = useState(false); const [saving, setSaving] = useState(false);
  const [razonSocial, setRazonSocial] = useState(''); const [nombreFantasia, setNombreFantasia] = useState(''); const [ruc, setRuc] = useState(''); const [monedaBase, setMonedaBase] = useState<CurrencyCode>('PYG');
  const load = useCallback(async () => { setStatus('loading'); setError(''); try { const body = await apiGet<{ data: Empresa[] }>('/empresas', token); setEmpresas(body.data); setStatus('ready'); } catch (failure) { setError(failure instanceof ApiError ? failure.message : tMsg('No se pudieron cargar las empresas.')); setStatus('error'); } }, [token]);
  useEffect(() => { void load(); }, [load]);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(''); try { await apiPost('/empresas', { razonSocial, nombreFantasia: nombreFantasia || undefined, ruc: ruc || undefined, documentoPrincipal: ruc || undefined, tipoDocumento: ruc ? 'RUC' : undefined, monedaBase }, token); setCreating(false); setRazonSocial(''); setNombreFantasia(''); setRuc(''); await load(); onChanged(); } catch (failure) { setError(failure instanceof ApiError ? failure.message : tMsg('No se pudo crear la empresa.')); } finally { setSaving(false); } }
  return <><header className="ds-page-header"><div className="ds-page-header__text"><h1 className="ds-title">{t('Empresas del grupo')}</h1><p className="ds-secondary">{t('Cada empresa comparte el tenant, pero conserva sus propios datos y movimientos.')}</p></div><button type="button" className="ds-btn ds-btn--primary" onClick={() => setCreating(true)}>{t('Nueva empresa')}</button></header>{error && <div className="ds-alert ds-alert--danger"><div className="ds-alert__body"><p>{error}</p></div></div>}{status === 'loading' ? <div className="ds-card"><div className="ds-card__body"><div className="ds-skeleton" style={{ height: '6rem' }} /></div></div> : <section className="ds-card"><div className="ds-table-wrap" style={{ border: 0 }}><table className="ds-table ds-table--cards"><thead><tr><th>{t('Razón social')}</th><th>{t('RUC')}</th><th>{t('Moneda base')}</th><th>{t('Estado')}</th></tr></thead><tbody>{empresas.map((empresa) => <tr key={empresa.id}><td className="is-strong" data-label={t('Razón social')}>{empresa.razon_social}<span className="ds-help" style={{ display: 'block' }}>{empresa.nombre_fantasia ?? t('Sin nombre de fantasía')}</span></td><td data-label={t('RUC')}>{empresa.ruc ?? '—'}</td><td data-label={t('Moneda')}>{empresa.moneda_base}</td><td data-label={t('Estado')}><span className={`ds-badge ds-badge--${empresa.activa ? 'pagado' : 'vencido'}`}>{empresa.activa ? t('Activa') : t('Inactiva')}</span></td></tr>)}</tbody></table></div></section>}{creating && <Modal title={t('Nueva empresa')} onClose={() => setCreating(false)}><form className="ds-modal__body" onSubmit={submit}><div className="ds-field"><label className="ds-label">{t('Razón social')}</label><input className="ds-input" value={razonSocial} onChange={(event) => setRazonSocial(event.target.value)} required autoFocus /></div><div className="ds-field"><label className="ds-label">{t('Nombre de fantasía')} <span className="ds-label__optional">{t('(opcional)')}</span></label><input className="ds-input" value={nombreFantasia} onChange={(event) => setNombreFantasia(event.target.value)} /></div><div className="ds-form-grid"><div className="ds-field ds-col-6"><label className="ds-label">{t('RUC')}</label><input className="ds-input" value={ruc} onChange={(event) => setRuc(event.target.value)} /></div><div className="ds-field ds-col-6"><label className="ds-label">{t('Moneda base')}</label><select className="ds-select" value={monedaBase} onChange={(event) => setMonedaBase(event.target.value as CurrencyCode)}><option value="PYG">PYG</option><option value="USD">USD</option><option value="BRL">BRL</option></select></div></div><footer className="ds-modal__footer"><button type="button" className="ds-btn ds-btn--secondary" onClick={() => setCreating(false)}>{t('Cancelar')}</button><button className="ds-btn ds-btn--primary" disabled={saving}>{saving ? t('Guardando…') : t('Crear empresa')}</button></footer></form></Modal>}</>;
}
