-- ============================================================================
-- `public` — o que é do BANCO, existe uma vez só
-- ============================================================================
--
-- Roda com `npm run migrate:public`. Nada aqui pertence a um cliente: são os
-- objetos que todos os tenants compartilham.
--
-- Se você for acrescentar tabela aqui, faça a pergunta antes: *dois clientes
-- diferentes veriam a mesma linha?* Se a resposta for não, o lugar é
-- `migrations/tenant/`.
-- ============================================================================

-- Registro de tenants: quem é quem e em que schema mora.
CREATE TABLE IF NOT EXISTS public.tenants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(200) NOT NULL,
  ruc VARCHAR(20),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  master_empresa_id INTEGER NOT NULL UNIQUE,
  login_schema VARCHAR(63) NOT NULL,
  CONSTRAINT tenants_master_empresa_matches_id CHECK (id = master_empresa_id),
  CONSTRAINT tenants_login_schema_format CHECK (login_schema ~ '^[a-z_][a-z0-9_]*$')
);

ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenants FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_self ON public.tenants;
CREATE POLICY tenant_self ON public.tenants
  USING (id = NULLIF(current_setting('app.tenant_id', true), '')::BIGINT)
  WITH CHECK (id = NULLIF(current_setting('app.tenant_id', true), '')::BIGINT);

-- Modelos de plano de contas. Servem a qualquer tenant; cada um copia o seu
-- na primeira empresa criada.
CREATE TABLE IF NOT EXISTS public.plantillas_plan_cuentas (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL UNIQUE,
  pais CHAR(2) NOT NULL DEFAULT 'PY',
  activa BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS public.plantillas_plan_cuentas_items (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  plantilla_id BIGINT NOT NULL REFERENCES public.plantillas_plan_cuentas(id) ON DELETE CASCADE,
  codigo VARCHAR(20) NOT NULL,
  descripcion VARCHAR(200) NOT NULL,
  naturaleza CHAR(1) NOT NULL CHECK (naturaleza IN ('R', 'D')),
  nivel SMALLINT NOT NULL CHECK (nivel BETWEEN 1 AND 3),
  id_padre BIGINT REFERENCES public.plantillas_plan_cuentas_items(id),
  UNIQUE (plantilla_id, codigo)
);
