ALTER TABLE public.tenants ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE public.tenants ADD COLUMN master_empresa_id INTEGER NOT NULL UNIQUE;
ALTER TABLE public.tenants ADD CONSTRAINT tenants_master_empresa_matches_id CHECK (id = master_empresa_id);
COMMENT ON COLUMN public.tenants.master_empresa_id IS 'ID de public.empresas no banco master SoftHam; é a chave de roteamento e isolamento do tenant.';

ALTER TABLE public.usuarios ADD COLUMN master_usuario_id INTEGER NOT NULL UNIQUE;
ALTER TABLE public.usuarios ADD COLUMN sobrenome VARCHAR(150) NOT NULL DEFAULT '';
ALTER TABLE public.usuarios DROP COLUMN password_hash;
COMMENT ON COLUMN public.usuarios.master_usuario_id IS 'ID de public.usuarios no banco master SoftHam. Senhas nunca são copiadas para este banco.';

ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usuarios FORCE ROW LEVEL SECURITY;
CREATE POLICY master_user_self ON public.usuarios
  USING (master_usuario_id = NULLIF(current_setting('app.user_id', true), '')::INTEGER)
  WITH CHECK (master_usuario_id = NULLIF(current_setting('app.user_id', true), '')::INTEGER);
