import { FormEvent, useMemo, useState } from 'react';
import { toMinorUnits } from '../design-system/format';
import { ApiError } from '../lib/api';
import { createCaja, createMovimiento, createTransferencia } from '../lib/operations';
import type { Caja } from '../lib/operations';
import { Modal } from './Modal';
import { useI18n } from '../i18n/useI18n';
import { t as tMsg } from '../i18n/translate';

type Mode = 'caja' | 'movimiento' | 'transferencia';

export function CajaActionForm({ mode, token, empresaId, cajas, onClose, onDone }: { mode: Mode; token: string; empresaId: number; cajas: Caja[]; onClose: () => void; onDone: () => void }) {
  const { t } = useI18n();
  const today = new Date().toISOString().slice(0, 10); const [nombre,setNombre]=useState(''); const [tipoCaja,setTipoCaja]=useState<'caja'|'banco'>('caja'); const [moneda,setMoneda]=useState<'PYG'|'USD'|'BRL'>('PYG'); const [importe,setImporte]=useState(''); const [fecha,setFecha]=useState(today); const [historico,setHistorico]=useState(''); const [documento,setDocumento]=useState(''); const [tipoMovimiento,setTipoMovimiento]=useState<'C'|'D'>('C'); const [cajaId,setCajaId]=useState(''); const [destinoId,setDestinoId]=useState(''); const [error,setError]=useState(''); const [saving,setSaving]=useState(false);
  const selected = cajas.find((item) => item.id === cajaId); const possibleDestinations = useMemo(() => cajas.filter((item) => item.id !== cajaId && item.moneda === selected?.moneda), [cajas,cajaId,selected?.moneda]);
  const title = mode === 'caja' ? t('Nueva caja o banco') : mode === 'movimiento' ? t('Nuevo movimiento manual') : t('Nueva transferencia');
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const currency = mode === 'caja' ? moneda : selected?.moneda; const minor = toMinorUnits(importe,currency ?? 'PYG'); if(!minor || (mode !== 'caja' && BigInt(minor)<=0n)){setError(tMsg('Ingresá un importe mayor que cero.'));return;} setSaving(true); try {
    if(mode==='caja') await createCaja(token,{empresaId,nombre,tipo:tipoCaja,moneda,saldoInicialMinor:minor,fechaSaldoInicial:fecha});
    else if(mode==='movimiento'){if(!selected)throw new Error(tMsg('Seleccione una caja.'));await createMovimiento(token,{empresaId,cajaId:Number(cajaId),fecha,historico,tipo:tipoMovimiento,moneda:selected.moneda,valorMinor:minor,documento:documento || undefined});}
    else {if(!selected || !destinoId)throw new Error(tMsg('Seleccione las dos cajas.'));await createTransferencia(token,{empresaId,cajaOrigenId:Number(cajaId),cajaDestinoId:Number(destinoId),fecha,valorMinor:minor,historico});}
    onDone();onClose();
  }catch(failure){setError(failure instanceof ApiError?failure.message:(failure as Error).message || tMsg('No se pudo guardar.'));}finally{setSaving(false);}}
  return <Modal title={title} onClose={onClose}><form className="ds-modal__body" onSubmit={submit}>
    {mode==='caja' && <><div className="ds-field"><label className="ds-label">{t('Nombre')}</label><input className="ds-input" value={nombre} onChange={e=>setNombre(e.target.value)} placeholder={t('Ej.: Banco Itaú · cuenta corriente')} required autoFocus /></div><div className="ds-form-grid"><div className="ds-field ds-col-6"><label className="ds-label">{t('Tipo')}</label><select className="ds-select" value={tipoCaja} onChange={e=>setTipoCaja(e.target.value as 'caja'|'banco')}><option value="caja">{t('Caja')}</option><option value="banco">{t('Banco')}</option></select></div><div className="ds-field ds-col-6"><label className="ds-label">{t('Moneda')}</label><select className="ds-select" value={moneda} onChange={e=>setMoneda(e.target.value as typeof moneda)}><option value="PYG">PYG</option><option value="USD">USD</option><option value="BRL">BRL</option></select></div><div className="ds-field ds-col-6"><label className="ds-label">{t('Saldo inicial')}</label><div className="ds-money-input"><span className="ds-money-input__prefix">{moneda}</span><input className="ds-input" inputMode="decimal" value={importe} onChange={e=>setImporte(e.target.value)} placeholder="0" required /></div></div><div className="ds-field ds-col-6"><label className="ds-label">{t('Fecha de saldo inicial')}</label><input className="ds-input" type="date" value={fecha} onChange={e=>setFecha(e.target.value)} required /></div></div></>}
    {mode!=='caja' && <><div className="ds-field"><label className="ds-label">{mode==='transferencia'?t('Caja de origen'):t('Caja')}</label><select className="ds-select" value={cajaId} onChange={e=>{setCajaId(e.target.value);setDestinoId('');}} required><option value="">{t('Seleccionar…')}</option>{cajas.map(c=><option key={c.id} value={c.id}>{c.nombre} · {c.moneda}</option>)}</select></div>{mode==='transferencia'&&<div className="ds-field"><label className="ds-label">{t('Caja de destino')}</label><select className="ds-select" value={destinoId} onChange={e=>setDestinoId(e.target.value)} required disabled={!selected}><option value="">{t('Seleccionar…')}</option>{possibleDestinations.map(c=><option key={c.id} value={c.id}>{c.nombre} · {c.moneda}</option>)}</select><p className="ds-field__hint">{t('Solo se permiten transferencias entre cajas de la misma moneda.')}</p></div>}{mode==='movimiento'&&<div className="ds-field"><label className="ds-label">{t('Tipo')}</label><select className="ds-select" value={tipoMovimiento} onChange={e=>setTipoMovimiento(e.target.value as 'C'|'D')}><option value="C">{t('Entrada (crédito)')}</option><option value="D">{t('Salida (débito)')}</option></select></div>}<div className="ds-field"><label className="ds-label">{t('Concepto')}</label><input className="ds-input" value={historico} onChange={e=>setHistorico(e.target.value)} placeholder={mode==='transferencia'?t('Transferencia entre cuentas'):t('Ej.: Reposición de caja')} required /></div><div className="ds-form-grid"><div className="ds-field ds-col-6"><label className="ds-label">{t('Importe')} {selected&&`(${selected.moneda})`}</label><div className="ds-money-input"><span className="ds-money-input__prefix">{selected?.moneda ?? '—'}</span><input className="ds-input" inputMode="decimal" value={importe} onChange={e=>setImporte(e.target.value)} required /></div></div><div className="ds-field ds-col-6"><label className="ds-label">{t('Fecha')}</label><input className="ds-input" type="date" value={fecha} onChange={e=>setFecha(e.target.value)} required /></div>{mode==='movimiento'&&<div className="ds-field ds-col-12"><label className="ds-label">{t('Documento (opcional)')}</label><input className="ds-input" value={documento} onChange={e=>setDocumento(e.target.value)} /></div>}</div></>}
    {error&&<div className="ds-alert ds-alert--danger" role="alert"><div className="ds-alert__body"><p>{error}</p></div></div>}<footer className="ds-modal__footer"><button type="button" className="ds-btn ds-btn--secondary" onClick={onClose}>{t('Cancelar')}</button><button type="submit" className="ds-btn ds-btn--primary" disabled={saving}>{saving?t('Guardando…'):t('Guardar')}</button></footer>
  </form></Modal>;
}
